##Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('car_price_cleaned.csv')
df.head()

,Car Make,Car Model,Year,Engine Size (L),Horsepower,Torque (lb-ft),0-60 MPH Time (seconds),Price (in USD),Powertrain Type
0,Porsche,911,2022,3.0,379.0,331.0,4.0,101200.0,ICE
1,Lamborghini,Huracan,2021,5.2,630.0,443.0,2.8,274390.0,ICE
2,Ferrari,488 GTB,2022,3.9,661.0,561.0,3.0,333750.0,ICE
3,Audi,R8,2022,5.2,562.0,406.0,3.2,142700.0,ICE
4,McLaren,720S,2021,4.0,710.0,568.0,2.7,298000.0,ICE

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Car Make                 1007 non-null   object
 1   Car Model                1007 non-null   object
 2   Year                     1007 non-null   int64
 3   Engine Size (L)          1007 non-null   float64
 4   Horsepower               1007 non-null   float64
 5   Torque (lb-ft)           1007 non-null   float64
 6   0-60 MPH Time (seconds)  1007 non-null   float64
 7   Price (in USD)           1007 non-null   float64
 8   Powertrain Type          1007 non-null   object
dtypes: float64(5), int64(1), object(3)
memory usage: 70.9+ KB

In [4]:
df['Car Age'] = 2026 - df['Year']

df.head()

,Car Make,Car Model,Year,Engine Size (L),Horsepower,Torque (lb-ft),0-60 MPH Time (seconds),Price (in USD),Powertrain Type,Car Age
0,Porsche,911,2022,3.0,379.0,331.0,4.0,101200.0,ICE,4
1,Lamborghini,Huracan,2021,5.2,630.0,443.0,2.8,274390.0,ICE,5
2,Ferrari,488 GTB,2022,3.9,661.0,561.0,3.0,333750.0,ICE,4
3,Audi,R8,2022,5.2,562.0,406.0,3.2,142700.0,ICE,4
4,McLaren,720S,2021,4.0,710.0,568.0,2.7,298000.0,ICE,5

In [5]:
from google.colab import files

df.to_csv("car_price_engineered.csv", index=False)
files.download("car_price_engineered.csv")